// src/app/layout.tsx
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ServicesSection from "@/components/Services/ServicesSection";
import AboutUs from "@/components/AboutUs";
import Header from "@/components/Header";
import TeleClinicHeroSection from "@/components/TeleClinicHeroSection";


// Properly configuring the Outfit font
const outfit = Outfit({
  weight: ["400"], // Use an array for multiple weights, if needed
  subsets: ["latin"], // Ensure the subset matches your font requirements
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <Header />
        <Navbar />
        <TeleClinicHeroSection />
        <ServicesSection />
        <AboutUs />
      {children}
        <Footer />
      </body>
    </html>
  );
}


